# Workshop 0.3: Dictionaries and Functions

Welcome to Workshop 0.3! So far in our coding journey, we have explored how to store isolated numbers in variables and how to gather items into ordered lists. We have also seen how loops help us step through collections without repeating ourselves.

### Looking Up Assets by Name

Imagine we want to track the latest closing prices for several tech stocks. If we rely solely on lists, we might keep two separate collections: one list for symbols and another list for prices. When we want to check the price of Microsoft, we must first remember that it sits at index 1 in the symbols list, and then retrieve index 1 from the prices list.

As our portfolio expands to hundreds of tickers, coordinating parallel lists becomes clumsy and invites errors. What we really need is a direct lookup system where we ask for an asset by its ticker symbol and instantly receive its price.

In Python, this tool is called a **dictionary**. Alongside dictionaries, we will build custom reusable calculation tools known as **functions**, allowing us to run trading calculations without rewriting code.

> **Key Takeaway**: Dictionaries let us look up values by meaningful labels rather than numerical positions, while functions package our calculations into reusable tools.

## Topic 1: Creating a Dictionary

Think of a Python **dictionary** like an index card Rolodex or price tags on a trading desk. Instead of relying on a numerical position, we look up a specific label to discover its associated information.

In programming terms, we call this connection a **key-value pair**:
- **Key**: The unique identifier or label we search for, such as the stock symbol `"AAPL"`.
- **Value**: The data linked to that label, such as the stock price `150.0`.

To build a dictionary, we enclose our pairs in curly braces `{` and `}`, join each key to its value with a colon `:`, and separate entries with commas.

Let's create our first dictionary of stock prices and inspect its structure. Let's see:

In [1]:
# We create a dictionary mapping stock tickers to their market prices
prices = {"AAPL": 150.0, "MSFT": 400.0, "GOOGL": 280.0}

# Let's display the full dictionary on screen
print(prices)

{'AAPL': 150.0, 'MSFT': 400.0, 'GOOGL': 280.0}


> **Key Takeaway**: A dictionary pairs unique keys with values inside curly braces, making data retrieval intuitive and direct.

---

## Topic 2: Accessing and Adding Values

With lists, we retrieve elements using their zero-based index number like `tickers[0]`. With dictionaries, we fetch elements directly by passing the key name inside square brackets: `dictionary[key]`.

If you ever wonder why square brackets are used for lookup even though the dictionary was built with curly braces, do not worry. This syntax often catches beginners off guard! Just remember: curly braces define the dictionary, while square brackets perform lookups.

Let's look up the price for Apple directly by its key name. Let's see:

In [2]:
# We retrieve the price for AAPL using its key name
print(prices["AAPL"])

150.0


### Adding a New Key-Value Pair

Market watchlists expand regularly as new opportunities emerge. Adding a fresh stock to our dictionary requires only a single assignment line: `dictionary[new_key] = new_value`.

Think of this like slipping a new price tag into our catalog. If the key is new, Python inserts it neatly; if the key already exists, Python updates its value.

Let's add NVIDIA (`"NVDA"`) with a price of `130.0` to our dictionary. Let's check:

In [3]:
# We add NVDA with its corresponding price of 130.0
prices["NVDA"] = 130.0

# Let's inspect our updated dictionary
print(prices)

{'AAPL': 150.0, 'MSFT': 400.0, 'GOOGL': 280.0, 'NVDA': 130.0}


> **Key Takeaway**: We access or add dictionary elements using square brackets with the key name, keeping lookup fast and expressive.

---

## Topic 3: Looping Over a Dictionary

Just as we iterated over lists, we can step through dictionaries using a `for` loop. When we iterate through a dictionary directly, Python hands us each **key** one pass at a time.

Once we hold the key in our loop variable, we can fetch its matching value using standard bracket lookup `prices[ticker]`.

Let's watch our loop visit each stock key and display its market price. Let's see:

In [4]:
# ticker receives each key, and prices[ticker] fetches the associated price
for ticker in prices:
  print(ticker, prices[ticker])

AAPL 150.0
MSFT 400.0
GOOGL 280.0
NVDA 130.0


### Polishing Output with f-strings

We can combine dictionary iteration with formatted strings from our earlier lessons to build a clear, readable price board.

Let's see how our market report looks when properly formatted:

In [5]:
# We format our stock ticker and currency price cleanly
for ticker in prices:
  print(f"Stock: {ticker} | Price: ${prices[ticker]:.2f}")

Stock: AAPL | Price: $150.00
Stock: MSFT | Price: $400.00
Stock: GOOGL | Price: $280.00
Stock: NVDA | Price: $130.00


> **Key Takeaway**: Looping over a dictionary yields each key, which allows us to access corresponding values dynamically.

---

## Topic 4: Defining a Simple Function

Up to this point, we have relied on Python's built-in functions like `print()` and `len()`. Now we take a major step forward by designing our own custom tools: **functions**.

Think of a function like a dedicated formula machine on a trading floor. You feed it inputs, it carries out your calculation, and it delivers back a result. Defining a function once allows us to reuse that exact calculation across multiple assets without copying code.

### Anatomy of a Function

Here is the standard anatomy of a function:

```python
def add(a, b):
    return a + b
```

Let's look at each component:
- **`def`**: Short for *define*, telling Python we are creating a new tool.
- **`add`**: The name we assign to our function so we can call it later.
- **`(a, b)`**: The input parameters our function expects.
- **The Colon `:`**: Signals that our header is complete and our indented instructions follow.
- **`return`**: Hands the computed output back to whoever called the function.

A common point of confusion for beginners is the difference between `print()` and `return`. While `print()` merely shows text on screen, `return` actually passes data back into our program so we can store it in a variable.

Let's define our addition function and test it with sample numbers. Let's see:

In [6]:
# We define a function named add that accepts two inputs and returns their sum
def add(a, b):
  return a + b

# We call our function with sample numbers
result = add(5, 3)

# Let's display the computed output
print(result)

8


### Reusing Your Function

Because `add` is now part of our active toolkit, we can call it as many times as we like with different values.

Let's run a couple of additional calculations to observe its flexibility. Let's check:

In [7]:
# We reuse our add function across different numeric inputs
print(add(150.0, 2.5))
print(add(1000, 500))

152.5
1500


> **Key Takeaway**: Functions package logic under a chosen name, using `def` to establish inputs and `return` to deliver results.

---

## Topic 5: Functions with a Loop

Functions become even more powerful when they wrap repetitive loops inside their body. Instead of rewriting loop logic every time we receive new data, we wrap the loop into a single function call.

This practice keeps our trading scripts clean and easy to maintain.

Let's build a reusable reporting function that accepts any dictionary and prints every entry. Let's see:

In [8]:
# We define a function that iterates through any supplied dictionary
def print_all(prices_dict):
  for key in prices_dict:
    print(key, prices_dict[key])

# We pass our prices dictionary into our new function
print_all(prices)

AAPL 150.0
MSFT 400.0
GOOGL 280.0
NVDA 130.0


> **Key Takeaway**: Combining functions with loops allows us to run multi-step data tasks across different datasets in a single call.

---

## Practice Time

Working through challenges on your own builds real muscle memory. If your code produces an error at first, treat it as helpful feedback. Finding and resolving small mistakes is how every quant builds mastery.

---

### Challenge 1: Mapping Trading Volumes

- Create a dictionary named `volumes` mapping these three stocks to their trading volumes:
  - `"AAPL"`: `5000000`
  - `"MSFT"`: `3200000`
  - `"GOOGL"`: `1800000`
- Write a `for` loop to print each ticker alongside its volume.

In [ ]:
# Challenge 1: Write your code below this line


# Expected Output:
# AAPL 5000000
# MSFT 3200000
# GOOGL 1800000


### Challenge 2: Doubling Stock Prices

- Define a function named `multiply_by_two(x)` that takes a number `x` and returns `x * 2`.
- Test your function by calling it with a sample price like `150.0` and print the outcome.

In [ ]:
# Challenge 2: Write your code below this line


# Expected Output:
# 300.0


### Challenge 3: Summing a Price Portfolio

- Write a function named `sum_prices(prices_list)` that:
  - Accepts a list of price numbers.
  - Initializes an accumulator `total = 0.0`.
  - Uses a `for` loop to add each price to `total`.
  - Returns `total`.
- Test your function with `[150.0, 400.0, 280.0, 130.0]` and print the sum.

In [ ]:
# Challenge 3: Write your code below this line


# Expected Output:
# 960.0


---

## Solutions Section

Terrific work tackling these exercises! In programming, slight stylistic differences in variable names are completely normal as long as your logic remains sound.

Let's review the reference implementations together.

### Reference Code

#### Solution for Challenge 1:
```python
volumes = {"AAPL": 5000000, "MSFT": 3200000, "GOOGL": 1800000}
for ticker in volumes:
    print(ticker, volumes[ticker])
```

#### Solution for Challenge 2:
```python
def multiply_by_two(x):
    return x * 2

price = 150.0
print(multiply_by_two(price))
```

#### Solution for Challenge 3:
```python
def sum_prices(prices_list):
    total = 0.0
    for price in prices_list:
        total = total + price
    return total

test_prices = [150.0, 400.0, 280.0, 130.0]
print(sum_prices(test_prices))
```

---

### Running the Solutions

Let's run each solution cell to verify our expected outputs:

In [9]:
# Solution for Challenge 1:
volumes = {"AAPL": 5000000, "MSFT": 3200000, "GOOGL": 1800000}
for ticker in volumes:
  print(ticker, volumes[ticker])

AAPL 5000000
MSFT 3200000
GOOGL 1800000


In [10]:
# Solution for Challenge 2:
def multiply_by_two(x):
  return x * 2

price = 150.0
print(multiply_by_two(price))

300.0


In [11]:
# Solution for Challenge 3:
def sum_prices(prices_list):
  total = 0.0
  for price in prices_list:
    total = total + price
  return total

test_prices = [150.0, 400.0, 280.0, 130.0]
print(sum_prices(test_prices))

960.0
