# Welcome to Python!

Welcome to the very start of your quantitative journey! If you have never written a single line of code before, take a deep breath: you are in the exact right place. Everyone who has ever built an automated trading system or analyzed a portfolio started right here with a blank screen.

Learning to code can feel unfamiliar at first, almost like learning a new spoken language. You might see strange error messages or wonder why a missing quotation mark stops an entire script. That is completely normal. The computer is not judging you; it is simply a very literal machine. With a little patience, thinking in code will quickly become second nature.

### Why We Program
In finance, we often deal with thousands of stock prices, interest rates, and trade orders. Doing these calculations by hand or in a spreadsheet becomes slow and error-prone very quickly. We write code so we can delegate repetitive mathematical tasks to an obedient assistant who can crunch millions of numbers in milliseconds without getting tired.

Python is the language we use to give clear, step-by-step instructions to that assistant.

### How We Work in a Jupyter Notebook
This document is an interactive workspace called a **Jupyter Notebook**. It lets us blend narrative explanations with live, runnable Python code.

The gray boxes below are **code cells**. Whenever we want Python to execute our instructions, we click inside the cell and press **Shift + Enter** on our keyboard. Python will immediately run the code and display the result directly underneath.

Let's begin by writing our very first instruction!

## Topic 1: The print() Function

When Python runs a calculation in the background, it keeps the result in memory silently. If we want to actually see what happened, we have to tell Python to speak up.

That is why we use `print()`. It is our window into the computer's mind, instructing it to display text or numbers on our screen.

Whenever we want to print text, like words or sentences, we wrap our message in quotation marks. That tells Python: "Treat this as plain human language, not as a programming command." If we want to leave notes for ourselves or our team, we start a line with a `#` symbol. Python ignores everything after the `#`, making it the perfect place to explain our thinking.

Let's check our first output below:

In [ ]:
# Let's ask Python to display our very first welcome message:
print("Hello, Pythoneers!")

Hello, Pythoneers!


### Printing Numbers Without Quotes

Numbers are a little different from words. When we work with numbers in finance, like share quantities or prices, we want Python to treat them as real mathematical values so we can add or multiply them later.

Because of this, we never put quotation marks around numbers. If we wrote `"42"`, Python would treat it like a word made of two characters rather than the quantity forty-two.

Let's see what happens when we print a number directly:

In [ ]:
# We can print numbers directly without quotes so Python knows they are numeric:
print(42)

42


> **Key Takeaway**: We use `print()` to display results on our screen. Text always goes inside quotation marks, while numbers stand on their own.

---

## Topic 2: Variables: Labeled Storage Boxes

Stock prices change every fraction of a second. If Apple trades at $150 in the morning and $155 in the afternoon, we do not want to rewrite all our trading formulas from scratch. We need a way to store a value, give it a name, and update it whenever the market moves.

In Python, we call this a **variable**. You can think of a variable as a labeled storage box on your desk. You write a label on the front, like `ticker` or `price`, and drop a piece of information inside. Whenever you need that information later, you just refer to the label on the box.

### The Assignment Operator (=)
In math class, the `=` sign means two things are equal. In Python, `=` has a very different meaning. We call it the **assignment operator**.

When you see `=`, read it as an action: "Take the value on the right side, and place it into the storage box on the left side."

Let's store a stock ticker symbol and check what is inside the box:

In [3]:
# We create a storage box labeled 'ticker' and place "AAPL" inside it:
ticker = "AAPL"

# Let's inspect what is currently stored inside our 'ticker' box:
print(ticker)

AAPL


Now let's create another storage box, this time for a stock price. We will label our box `price` and store a decimal value inside it.

Let's see how this works in practice:

In [4]:
# We place the current share price into a box labeled 'price':
price = 150.25

# Let's check the price:
print(price)

150.25


### Updating What Is in the Box

Why do we call these containers *variables*? Because the value inside can **vary** over time.

If Apple's stock price rallies later in the trading session, we do not need to create a whole new box. We simply assign the new price into the existing `price` box. Python will discard the old number and replace it with the new one.

Let's check how an update looks:

In [5]:
# The market moved, so we replace the old value in 'price' with a new one:
price = 155.00

# Let's check the updated price:
print(price)

155.0


> **Key Takeaway**: Variables are labeled storage boxes in memory. We use the `=` sign to put information inside them, and we can update their contents whenever market conditions change.

---

## Topic 3: Data Types

In our daily lives, we intuitively understand that a company's name, a count of shares, and a price in dollars are completely different kinds of information. You cannot multiply a company name by two, but you can certainly multiply a price by two.

Python makes this same distinction through **data types**. Knowing your data type is essential in quantitative finance because applying math to the wrong type of data is one of the most common beginner errors.

Here are the three fundamental types we rely on every day:
- **Integer (`int`)**: Whole counting numbers with no decimal point, such as buying `100` shares.
- **Float (`float`)**: Numbers with decimal points (short for *floating-point number*), such as a stock price of `$150.25`.
- **String (`str`)**: Plain text wrapped in quotation marks, such as a ticker symbol like `"AAPL"`.

Whenever we are unsure what kind of data is sitting in a variable, Python gives us a built-in detective tool: `type()`. We just put our variable inside `type()`, and Python tells us its classification.

Let's check each data type in action:

In [6]:
# Whole numbers without decimals are classified as integers ('int'):
print(type(42))

<class 'int'>


In [7]:
# Numbers with a decimal point are classified as floating-point numbers ('float'):
print(type(3.14))

<class 'float'>


In [8]:
# Any text wrapped in quotation marks is classified as a string ('str'):
print(type("AAPL"))

<class 'str'>


> **Key Takeaway**: Python categorizes data into types. We use `int` for whole share counts, `float` for dollar prices and returns, and `str` for ticker symbols. We can always inspect an object's type with `type()`.

---

## Topic 4: Basic Math

At its core, quantitative finance is all about arithmetic: calculating percentage changes, compounding returns, and sizing trade positions. Fortunately, Python works as an ultra-fast calculator that never makes an arithmetic mistake.

We use standard mathematical operators:
- `+` for addition
- `-` for subtraction
- `*` for multiplication (the asterisk key, Shift + 8)
- `/` for division (the forward slash)

Let's look at a common trading task: finding the dollar difference between a stock's opening price and its closing price.

Let's see how Python calculates this change:

In [9]:
# We store the market opening and closing prices:
open_price = 150.0
close_price = 152.5

# We calculate the price change by subtracting open from close:
change = close_price - open_price

# Let's check the result:
print(change)

2.5


### Multiplication and Division

We can also multiply and divide to model price targets or corporate actions.

For example, if we want to calculate what our stock price would be after a 2% rally, we multiply the current price by `1.02`. If a company announces a 2-for-1 stock split, the share price gets cut in half, so we divide by `2`.

Let's check these calculations:

In [10]:
price = 150.0

# We calculate a 2% price increase by multiplying by 1.02:
print(price * 1.02)

# We model a 2-for-1 stock split by dividing the price in half:
print(price / 2)

153.0
75.0


> **Key Takeaway**: We can perform arithmetic directly on variables holding numbers. Python uses `+`, `-`, `*`, and `/` for basic financial calculations.

---

## Topic 5: f-strings: Bringing Text and Numbers Together

When we build trade logs, risk alerts, or portfolio summaries, we rarely want to look at a bare number like `150.25` sitting alone on a screen. We want a clear, professional sentence: `"The price of AAPL is $150.25"`.

In modern Python, the cleanest and most elegant way to merge words and variables is with an **f-string** (short for *formatted string literal*).

You can think of an f-string like filling out a pre-printed trading ticket. You write out the text of your ticket, and wherever you need live data, you leave a set of curly braces `{}` with the variable's name inside. Python fills in the blanks automatically.

To create an f-string, we just put the letter `f` right before the opening quotation mark, like `f"..."`.

Let's see how an f-string looks in practice:

In [11]:
ticker = "AAPL"
price = 150.25

# We place 'f' before the quotes and tuck our variables inside curly braces {}:
print(f"The price of {ticker} is ${price}")

The price of AAPL is $150.25


### Formatting Currency to Two Decimal Places

In financial reports, floating-point numbers can sometimes look awkward. A price might print as `150.2` or even `150.200000000004` due to how computers store decimals in binary memory. In finance, we almost always want our dollar amounts formatted neatly to exactly two decimal places, representing dollars and cents.

Python makes this remarkably simple. Inside our curly braces, we can add a formatting rule right after the variable name: `{price:.2f}`.

The colon `:` tells Python that formatting instructions are coming. The `.2` means we want exactly two digits after the decimal point, and the `f` confirms that we are formatting a floating-point number.

Let's compare unformatted versus formatted output:

In [12]:
price = 150.2

# Let's check how the price looks without formatting:
print(f"Without formatting: ${price}")

# Now let's see how clean it looks when we enforce two decimal places:
print(f"With formatting: ${price:.2f}")

Without formatting: $150.2
With formatting: $150.20


> **Key Takeaway**: f-strings let us seamlessly blend text and variables into human-readable messages. Adding `:.2f` inside the braces guarantees clean financial formatting with two decimal places.

---

## Practice Time

Reading about code is a great start, but programming is a hands-on craft. The only way it truly sticks is by typing code yourself, making mistakes, and seeing how the computer responds.

Do not worry if you get stuck or see an error message. That is an essential part of the learning process. Take your time, try each challenge, and then check your work against the official solutions below.

---

### Challenge 1: Your First Stock Quote
Let's build a stock quote message:
- Create a variable named `ticker` and set it to `"MSFT"`.
- Create a variable named `price` and set it to `400.0`.
- Use an f-string to print: `The price of MSFT is $400.00` (make sure to format the price to two decimal places).

In [ ]:
# Practice 1: Write your code below this line


# Expected Output: The price of MSFT is $400.00

### Challenge 2: Calculating a Price Jump
Now let's practice doing math with our variables:
- Start with `price = 400.0`.
- Calculate a 2% price increase by multiplying `price` by `1.02`.
- Store the new value in a variable named `new_price`.
- Print `new_price`.

In [ ]:
# Practice 2: Write your code below this line


# Expected Output: 408.0

### Challenge 3: Trading Volume Report
Let's report daily trading activity:
- Create a variable named `volume` and set it to `5000000` (five million shares).
- Use an f-string to print: `Today's trading volume was 5000000 shares.`

In [ ]:
# Practice 3: Write your code below this line


# Expected Output: Today's trading volume was 5000000 shares.

---

## Solutions

Take a moment to review how our solutions are structured. Notice how each solution mirrors the patterns we explored earlier in the notebook.

### Solution to Challenge 1:
```python
ticker = "MSFT"
price = 400.0
print(f"The price of {ticker} is ${price:.2f}")
```
Explanation:
We store `"MSFT"` as a string and `400.0` as a float. Inside our f-string, `{ticker}` displays the company symbol and `{price:.2f}` rounds the decimal to cents.

---

### Solution to Challenge 2:
```python
price = 400.0
new_price = price * 1.02
print(new_price)
```
Explanation:
We take the original price of $400 and scale it by 1.02 to represent a 2% gain. We store that in `new_price` before printing.

---

### Solution to Challenge 3:
```python
volume = 5000000
print(f"Today's trading volume was {volume} shares.")
```
Explanation:
Because share volume is a whole count, we store `5000000` as an integer without quotes. Our f-string embeds the number cleanly into our sentence.

---

### Running the Solutions
Let's check the live code cells below to see the exact execution of each solution:

In [13]:
# Solution 1:
ticker = "MSFT"
price = 400.0
print(f"The price of {ticker} is ${price:.2f}")

The price of MSFT is $400.00


In [14]:
# Solution 2:
price = 400.0
new_price = price * 1.02
print(new_price)

408.0


In [15]:
# Solution 3:
volume = 5000000
print(f"Today's trading volume was {volume} shares.")

Today's trading volume was 5000000 shares.
